---
- hosts: app-server
  become: true
  tasks:
    - name: update the server apt
      command: sudo apt update
    - name: install docker in test server
      apt:
        pkg: docker.io
        state: present
    - name: run insure me in test server
      command: "docker run -itd -p 9090:8081 arungenie/insureme:1.0"
