---
- hosts: prod-server
  become: true
  tasks:
    -name: update the apt
     command: sudo apt update
    - name: install docker 
      apt:
        pkg: docker.io
        state: present
    - name: deploy the container
      command: "sudo docker run -itd -p 9090:8081 arungenie/insureme:1.0"
